{% set name = "veerer" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/veerer-{{ version }}.tar.gz
  sha256: e64b6559a8409d0c9616f1ca5e9e290e9223fdfcec13653b13502988d2461be9

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  # SageMath is not available on Windows. We could build veerer but it cannot
  # even be imported then without sagelib.
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - sagelib

test:
  imports:
    - veerer
  # pip check fails due to
  # https://github.com/conda-forge/sagelib-feedstock/issues/169. The
  # dependencies of veerer are all satisfied.
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/flatsurf/veerer
  summary: Veerer is a package for SageMath to deal with veering triangulations of surfaces and their associated flat structures.
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - saraedum
